config/routes.rb
Rails.application.routes.draw do
  resources :phones
  resources :emails
  resources :addresses
  resources :people
  resources :email_types
  resources :phone_types
  resources :address_types

  get "people/:name",  to: "people#show"
  get "people/:email", to: "people#show"

  scope '/api' do
    scope '/v1' do
      scope '/person' do
        get '/' => 'people#index'
        post '/' => 'people#create'
        scope '/:name' do
          get '/' => 'people#show'
          put '/' => 'people#update'
        end
      end 
    end
  end

end

app/controllers/email_types_controller.rb
class EmailTypesController < ApplicationController
  before_action :set_email_type, only: [:show, :edit, :update, :destroy]

  # GET /email_types
  # GET /email_types.json
  def index
    @email_types = EmailType.all
  end

  # GET /email_types/1
  # GET /email_types/1.json
  def show
  end

  # GET /email_types/new
  def new
    @email_type = EmailType.new
  end

  # GET /email_types/1/edit
  def edit
  end

  # POST /email_types
  # POST /email_types.json
  def create
    @email_type = EmailType.new(email_type_params)

    respond_to do |format|
      if @email_type.save
        format.html { redirect_to @email_type, notice: 'Email type was successfully created.' }
        format.json { render :show, status: :created, location: @email_type }
      else
        format.html { render :new }
        format.json { render json: @email_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_types/1
  # PATCH/PUT /email_types/1.json
  def update
    respond_to do |format|
      if @email_type.update(email_type_params)
        format.html { redirect_to @email_type, notice: 'Email type was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_type }
      else
        format.html { render :edit }
        format.json { render json: @email_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_types/1
  # DELETE /email_types/1.json
  def destroy
    @email_type.destroy
    respond_to do |format|
      format.html { redirect_to email_types_url, notice: 'Email type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_type
      @email_type = EmailType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_type_params
      params.require(:email_type).permit(:name)
    end
end

app/helpers/email_types_helper.rb
module EmailTypesHelper
end

app/views/email_types/_form.html.erb
<%= form_for(@email_type) do |f| %>
  <% if @email_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_type.errors.count, "error") %> prohibited this email_type from being saved:</h2>

      <ul>
      <% @email_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_types/edit.html.erb
<h1>Editing Email Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @email_type %> |
<%= link_to 'Back', email_types_path %>

app/views/email_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Email Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @email_types.each do |email_type| %>
      <tr>
        <td><%= email_type.name %></td>
        <td><%= link_to 'Show', email_type %></td>
        <td><%= link_to 'Edit', edit_email_type_path(email_type) %></td>
        <td><%= link_to 'Destroy', email_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Email type', new_email_type_path %>

app/views/email_types/new.html.erb
<h1>New Email Type</h1>

<%= render 'form' %>

<%= link_to 'Back', email_types_path %>

app/views/email_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @email_type.name %>
</p>

<%= link_to 'Edit', edit_email_type_path(@email_type) %> |
<%= link_to 'Back', email_types_path %>