config/routes.rb
Rails.application.routes.draw do
  resources :phones
  resources :emails
  resources :addresses
  resources :people
  resources :email_types
  resources :phone_types
  resources :address_types

  get "people/:name",  to: "people#show"
  get "people/:email", to: "people#show"

  scope '/api' do
    scope '/v1' do
      scope '/person' do
        get '/' => 'people#index'
        post '/' => 'people#create'
        scope '/:name' do
          get '/' => 'people#show'
          put '/' => 'people#update'
        end
      end 
    end
  end

end

app/controllers/phone_types_controller.rb
class PhoneTypesController < ApplicationController
  before_action :set_phone_type, only: [:show, :edit, :update, :destroy]

  # GET /phone_types
  # GET /phone_types.json
  def index
    @phone_types = PhoneType.all
  end

  # GET /phone_types/1
  # GET /phone_types/1.json
  def show
  end

  # GET /phone_types/new
  def new
    @phone_type = PhoneType.new
  end

  # GET /phone_types/1/edit
  def edit
  end

  # POST /phone_types
  # POST /phone_types.json
  def create
    @phone_type = PhoneType.new(phone_type_params)

    respond_to do |format|
      if @phone_type.save
        format.html { redirect_to @phone_type, notice: 'Phone type was successfully created.' }
        format.json { render :show, status: :created, location: @phone_type }
      else
        format.html { render :new }
        format.json { render json: @phone_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_types/1
  # PATCH/PUT /phone_types/1.json
  def update
    respond_to do |format|
      if @phone_type.update(phone_type_params)
        format.html { redirect_to @phone_type, notice: 'Phone type was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_type }
      else
        format.html { render :edit }
        format.json { render json: @phone_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_types/1
  # DELETE /phone_types/1.json
  def destroy
    @phone_type.destroy
    respond_to do |format|
      format.html { redirect_to phone_types_url, notice: 'Phone type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_type
      @phone_type = PhoneType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_type_params
      params.require(:phone_type).permit(:name)
    end
end

app/helpers/phone_types_helper.rb
module PhoneTypesHelper
end

app/views/phone_types/_form.html.erb
<%= form_for(@phone_type) do |f| %>
  <% if @phone_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_type.errors.count, "error") %> prohibited this phone_type from being saved:</h2>

      <ul>
      <% @phone_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_types/edit.html.erb
<h1>Editing Phone Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_type %> |
<%= link_to 'Back', phone_types_path %>

app/views/phone_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Phone Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_types.each do |phone_type| %>
      <tr>
        <td><%= phone_type.name %></td>
        <td><%= link_to 'Show', phone_type %></td>
        <td><%= link_to 'Edit', edit_phone_type_path(phone_type) %></td>
        <td><%= link_to 'Destroy', phone_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone type', new_phone_type_path %>

app/views/phone_types/new.html.erb
<h1>New Phone Type</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_types_path %>

app/views/phone_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @phone_type.name %>
</p>

<%= link_to 'Edit', edit_phone_type_path(@phone_type) %> |
<%= link_to 'Back', phone_types_path %>