config/routes.rb
Rails.application.routes.draw do
  resources :phones
  resources :emails
  resources :addresses
  resources :people
  resources :email_types
  resources :phone_types
  resources :address_types

  get "people/:name",  to: "people#show"
  get "people/:email", to: "people#show"

  scope '/api' do
    scope '/v1' do
      scope '/person' do
        get '/' => 'people#index'
        post '/' => 'people#create'
        scope '/:name' do
          get '/' => 'people#show'
          put '/' => 'people#update'
        end
      end 
    end
  end

end

app/controllers/address_types_controller.rb
class AddressTypesController < ApplicationController
  before_action :set_address_type, only: [:show, :edit, :update, :destroy]

  # GET /address_types
  # GET /address_types.json
  def index
    @address_types = AddressType.all
  end

  # GET /address_types/1
  # GET /address_types/1.json
  def show
  end

  # GET /address_types/new
  def new
    @address_type = AddressType.new
  end

  # GET /address_types/1/edit
  def edit
  end

  # POST /address_types
  # POST /address_types.json
  def create
    @address_type = AddressType.new(address_type_params)

    respond_to do |format|
      if @address_type.save
        format.html { redirect_to @address_type, notice: 'Address type was successfully created.' }
        format.json { render :show, status: :created, location: @address_type }
      else
        format.html { render :new }
        format.json { render json: @address_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /address_types/1
  # PATCH/PUT /address_types/1.json
  def update
    respond_to do |format|
      if @address_type.update(address_type_params)
        format.html { redirect_to @address_type, notice: 'Address type was successfully updated.' }
        format.json { render :show, status: :ok, location: @address_type }
      else
        format.html { render :edit }
        format.json { render json: @address_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /address_types/1
  # DELETE /address_types/1.json
  def destroy
    @address_type.destroy
    respond_to do |format|
      format.html { redirect_to address_types_url, notice: 'Address type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address_type
      @address_type = AddressType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_type_params
      params.require(:address_type).permit(:name)
    end
end

app/helpers/address_types_helper.rb
module AddressTypesHelper
end

app/views/address_types/_form.html.erb
<%= form_for(@address_type) do |f| %>
  <% if @address_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address_type.errors.count, "error") %> prohibited this address_type from being saved:</h2>

      <ul>
      <% @address_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/address_types/edit.html.erb
<h1>Editing Address Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @address_type %> |
<%= link_to 'Back', address_types_path %>

app/views/address_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Address Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @address_types.each do |address_type| %>
      <tr>
        <td><%= address_type.name %></td>
        <td><%= link_to 'Show', address_type %></td>
        <td><%= link_to 'Edit', edit_address_type_path(address_type) %></td>
        <td><%= link_to 'Destroy', address_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address type', new_address_type_path %>

app/views/address_types/new.html.erb
<h1>New Address Type</h1>

<%= render 'form' %>

<%= link_to 'Back', address_types_path %>

app/views/address_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @address_type.name %>
</p>

<%= link_to 'Edit', edit_address_type_path(@address_type) %> |
<%= link_to 'Back', address_types_path %>